#!/bin/sh

dmverity_enabled() {
    [ "${bootparam_root}" = "/dev/nfs" ] && return 1

    return 0
}

dmverity_resolve_device() {
    case "${bootparam_root}" in
        UUID=*)
            realpath "/dev/disk/by-uuid/${bootparam_root#UUID=}"
            ;;
        PARTUUID=*)
            realpath "/dev/disk/by-partuuid/${bootparam_root#PARTUUID=}"
            ;;
        PARTLABEL=*)
            realpath "/dev/disk/by-partlabel/${bootparam_root#PARTLABEL=}"
            ;;
        LABEL=*)
            realpath "/dev/disk/by-label/${bootparam_root#LABEL=}"
            ;;
        *)
            realpath "${bootparam_root}"
            ;;
    esac
}

verify_slot() {
    local dev data_size data_block_size root_hash
    
    dev="$1"
    data_size="$2"
    data_block_size="$3"
    root_hash="$4"

    dmsetup remove verity_test >/dev/null 2>&1

    veritysetup \
        --data-block-size="${data_block_size}" \
        --hash-offset="${data_size}" \
        create verity_test \
        "${dev}" \
        "${dev}" \
        "${root_hash}" >/dev/null 2>&1 || return 1

    mkdir -p /run/verity-test

    mount \
        -t squashfs \
        -o ro \
        /dev/mapper/verity_test \
        /run/verity-test >/dev/null 2>&1 || {
        dmsetup remove verity_test >/dev/null 2>&1
        return 1
    }

    dd if=/dev/mapper/verity_test \
        of=/dev/null \
        bs=8M \
        status=none >/dev/null 2>&1 || {
            umount /run/verity-test >/dev/null 2>&1
            dmsetup remove verity_test; 
            return 1;
        }

    umount /run/verity-test >/dev/null 2>&1
    dmsetup remove verity_test >/dev/null 2>&1

    return 0
}

mount_verified_rootfs() {
    local dev data_size data_block_size root_hash

    dev="$1"
    data_size="$2"
    data_block_size="$3"
    root_hash="$4"

    dmsetup remove rootfs >/dev/null 2>&1

    veritysetup \
        --data-block-size="${data_block_size}" \
        --hash-offset="${data_size}" \
        create rootfs \
        "${dev}" \
        "${dev}" \
        "${root_hash}" || return 1

    mount \
        -o ro \
        /dev/mapper/rootfs \
        "${ROOTFS_DIR}" || {
        dmsetup remove rootfs >/dev/null 2>&1
        return 1
    }

    return 0
}

wait_root_device() {
    local root_dev elapsed delay timeout

    root_dev="${1}"
    elapsed=0
    delay=${bootparam_rootdelay:-1}
    timeout=${bootparam_roottimeout:-5}

    while [ ! -b "${root_dev}" ]; do

        if [ "${elapsed}" -ge "${timeout}" ]; then
            return 1
        fi

        debug "Sleeping for ${delay} second(s) to wait root to settle..."
        sleep "${delay}"

        elapsed=$((elapsed + delay))
    done

    return 0
}

dmverity_run() {
    local root_dev

    . /usr/share/misc/dm-verity.env

    if [ -z "$DATA_SIZE" ] || [ -z "$DATA_BLOCK_SIZE" ] || [ -z "$ROOT_HASH" ]; then
        fatal "dm-verity env not found in u-boot"
    fi

    root_dev="$(dmverity_resolve_device)" || fatal "Root device resolution failed"

    wait_root_device "${root_dev}" || fatal "Root device ${root_dev} is not ready"

    verify_slot "${root_dev}" "${DATA_SIZE}" "${DATA_BLOCK_SIZE}" "${ROOT_HASH}" || fatal "${root_dev} failed dm-verity verification"

    mount_verified_rootfs "${root_dev}" "${DATA_SIZE}" "${DATA_BLOCK_SIZE}" "${ROOT_HASH}" || fatal "${root_dev} passed verification but mount failed"
}
