#!/bin/sh

dmverity_enabled() {
    return 0
}

dmverity_resolve_device() {
    case "${bootparam_root}" in
        UUID=*)
            realpath "/dev/disk/by-uuid/${bootparam_root#UUID=}"
            ;;
        PARTUUID=*)
            realpath "/dev/disk/by-partuuid/${bootparam_root#PARTUUID=}"
            ;;
        PARTLABEL=*)
            realpath "/dev/disk/by-partlabel/${bootparam_root#PARTLABEL=}"
            ;;
        LABEL=*)
            realpath "/dev/disk/by-label/${bootparam_root#LABEL=}"
            ;;
        *)
            realpath "${bootparam_root}"
            ;;
    esac
}

verify_slot() {
    local dev="$1"

    dmsetup remove verity_test >/dev/null 2>&1

    veritysetup \
        --data-block-size="${DATA_BLOCK_SIZE}" \
        --hash-offset="${DATA_SIZE}" \
        create verity_test \
        "${dev}" \
        "${dev}" \
        "${ROOT_HASH}" >/dev/null 2>&1 || return 1

    mkdir -p /run/verity-test

    mount \
        -t squashfs \
        -o ro \
        /dev/mapper/verity_test \
        /run/verity-test >/dev/null 2>&1 || {
        dmsetup remove verity_test >/dev/null 2>&1
        return 1
    }

    dd if=/dev/mapper/verity_test \
        of=/dev/null \
        bs=8M \
        status=none >/dev/null 2>&1 || { 
            dmsetup remove verity_test; 
            return 1;
        }

    umount /run/verity-test >/dev/null 2>&1
    dmsetup remove verity_test >/dev/null 2>&1

    return 0
}

wait_root_device() {
    local root_dev elapsed delay timeout

    root_dev="${1}"
    elapsed=0
    delay=${bootparam_rootdelay:-1}
    timeout=${bootparam_roottimeout:-5}

    while [ ! -b "${root_dev}" ]; do

        if [ "${elapsed}" -ge "${timeout}" ]; then
            return 1
        fi

        debug "Sleeping for ${delay} second(s) to wait root to settle..."
        sleep "${delay}"

        elapsed=$((elapsed + delay))
    done

    return 0
}

dmverity_run() {
    local root_dev

    . /usr/share/misc/dm-verity.env

    if [ -z "$DATA_SIZE" ] || [ -z "$DATA_BLOCK_SIZE" ] || [ -z "$ROOT_HASH" ]; then
        fatal "dm-verity env not found in u-boot"
    fi

    root_dev="$(dmverity_resolve_device)" || fatal "Root device resolution failed"

    wait_root_device "${root_dev}" || fatal "Root device ${root_dev} is not ready"

    verify_slot "${root_dev}" || fatal "rootfs slots failed dm-verity verification"

    dmsetup remove rootfs >/dev/null 2>&1

    veritysetup \
        --data-block-size="${DATA_BLOCK_SIZE}" \
        --hash-offset="${DATA_SIZE}" \
        create rootfs \
        "${root_dev}" \
        "${root_dev}" \
        "${ROOT_HASH}" || fatal "dm-verity setup failed"

    mount \
        -o ro \
        /dev/mapper/rootfs \
        "${ROOTFS_DIR}" || fatal "mount rootfs failed"
}
